spring.application.name=encryptiontool

spring.datasource.url=jdbc:mysql://localhost:3306/encryption_project
spring.datasource.username=root
spring.datasource.password=Admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8333
